### ISSUE TITLE
consider re(un)factoring

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#44]
The easiest way to incorporate this code into an Apps Script project is as a library, since it only needs to be maintained in one place that way.  (Granted, you forfeit the ability to step into routines in the debugger.)

With Apps Script, each call to a library routine needs to be prefaced by the name of that library.  This means that, if there are four files for olapscript, an Apps Script developer needs to be aware of which of the four files a particular routine lives in, so they can preface it with the correct library name.

For that reason, it might be preferable to have the code live in one file (say, "olapscript"), so that any call could be made by just prefacing it with that one prefix.

**Comment by presentoccupant** [comment]
The comment [here](https://support.google.com/docs/thread/13371261/how-do-i-use-one-google-apps-script-file-to-be-used-for-multiple-different-google-sheets?hl=en) by Jason @ xFanatical might suggest the best way to go.

**Comment by hawkfish** [comment]
> Warning: Once you save your visibility option during the publication process, you can't change your selection later. Make sure you know what visibility your add-on needs before you start the publication process

**Comment by hawkfish** [comment]
> [This video isn't available any more](https://youtu.be/TqWtSp4IJcg)

**Comment by hawkfish** [comment]
Sticking it all in one big library gets pretty unwieldy after a while, which is why I broke it up. But the import mechanisms in Apps Script are really at odds with how JavaScript works, which is a royal PITA.

**Comment by presentoccupant** [comment]
Workflow that bundles it into olapscript.gs seems like an excellent compromise; thanks.
