### ISSUE TITLE
ReferenceError: Unknown column: Email

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#57]
Please take a look at the mailchimp example in the ".pol" account.  Are lines 18 and 25 correct?  If so, the code throws the error in the subject line.  If not, please indicate what needs to be different.

**Comment by hawkfish** [comment]
This will have to wait until I'm in the office because I don't have that account set up on my laptop.

**Comment by hawkfish** [comment]
Did we address this?

**Comment by presentoccupant** [comment]
This is still throwing an error.  You can reproduce by locating the spreadsheet named "mailchimp example" and running the associated code.

**Comment by hawkfish** [comment]
Is this answered by #78

**Comment by presentoccupant** [comment]
No; it must have been something else that caused the error and subsequently got fixed, because it's working now (whereas the response to #78 is that olapscript doesn't work the way I expected it to).
