### ISSUE TITLE
something's funky with limit

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#58]
Using the testLimit code in olapscript-tests-and-utils: 

.limit(5, 1) returned:
blank row
row 5
row 6
row 2
row 8

.limit (5, 5) returned:
row 8
row 10
row 9
row 11
row 12

.limit (5) returned:
blank row
row 5
row 6
row 2
row 8

**Comment by hawkfish** [comment]
This is probably a duplicate of #60 .

**Comment by presentoccupant** [comment]
Tested and verified.
