### ISSUE TITLE
typeerror when running testDuplicateNames

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#60]
Running testDuplicateNames in olapscript-tests-and-utils and get the following error:

TypeError: Cannot read property 'map' of undefined
(anonymous)	@ olapscript.gs:1512
Table.groupby	@ olapscript.gs:1511
testDuplicateNames	@ olapscript-tests-and-utils.gs:136

**Comment by hawkfish** [comment]
Probably just the calling sequence changed.

**Comment by presentoccupant** [comment]
Table.fromSheet(ss.getSheetByName("Volunteers"))
       .groupby([new RefExpr("First"), new RefExpr("Last"), new RefExpr("Email")], CountStar)
       .having(new FuncExpr(x => x > 1, new RefExpr("CountStar")))
       .toSheet(target);

**Comment by hawkfish** [comment]
The problem looks to be that `fromSheet` doesn't use `getRange` correctly (the second arguments are counts, not indices).

**Comment by hawkfish** [comment]
Please check.

**Comment by presentoccupant** [comment]
Still getting an error here.
TypeError: Cannot read property 'map' of undefined
(anonymous)	@ olapscript.gs:1543  	aggr.func.args.map(arg =>
Table.groupby	@ olapscript.gs:1542  const inputs = aggrs.map(aggr =>
testDuplicateNames	@ olapscript-tests-and-utils.gs:137        .groupby([new RefExpr("First"), new RefExpr("Last"), new RefExpr("Email")], CountStar)

(I listed the line of code identified by each line number in case the line numbers aren't the same)

**Comment by hawkfish** [comment]
OK I see what is going on here now. I changed the way aggregates are built and they code is now a mix of the two formats.

**Comment by hawkfish** [comment]
Should be. working now.

**Comment by presentoccupant** [comment]
Tested and verified!
