### ISSUE TITLE
how to run the tests in /test?

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#61]
They aren't themselves functions that can be run, and it's not clear how to wire them up to be able to run them.

**Comment by hawkfish** [comment]
First check out the project and initialise node:

```sh
$ git clone git@github.com:hawkfish/olapscript.git
$ cd olapscript
$ npm init
```

Then you should be able to run the full test suite using `npm`:

```sh
npm test
```

To run smaller sets of tests, you can run `mocha` directly with the `-g` ("grep") options and provide a pattern to match.
