### ISSUE TITLE
please provide a way to configure up front so timezone defaults to <desired time zone>

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#63]
(in my case, Pacific)

**Comment by hawkfish** [comment]
`Expr` should just have a key/value store with things like `TimeZone`. Then `Expr.get` and `Expr.set` could access them.

**Comment by hawkfish** [comment]
It looks like time zones are pretty much impossible to deal with is standard JS. There are libraries that purport to Do The Right Thing, but I don't know if we can use them in GAS.

**Comment by hawkfish** [comment]
[This](https://stackoverflow.com/questions/12451292/time-zones-in-google-apps-script) was rather scary, but it looks like GAS is now JS compliant (instead of Excel compliant, which is what that 1899 business is all about...)

**Comment by hawkfish** [comment]
Maybe the best we can do here is [`make_timestamp` and `make_timestamptz`](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TABLE) The former would use UTC and the latter would use a specific time zone setting by  default.

**Comment by hawkfish** [comment]
One way to skin this would be to use `Date` string parser and feed it ISO times with offsets:

```js
const actual = new Date('2022-08-31 08:59:51 -0700');
const expected = new Date(Date.UTC(2022, 7, 31, 15, 59, 51));
expect(actual).to.deep.equal(expected);
```

Unfortunately, this relies on `Date.parse`, which is [known](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) to be inconsistent across browsers.

**Comment by hawkfish** [comment]
Wow Apps Script support for dates is so bad people suggest writing your own parser! Easy enough with a `RegExp` but DST is still an issue without a library.
