### ISSUE TITLE
query request

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#65]
Suppose you had a table that contained the following fields:
timestamp, firstName, lastName, email, date, field1, field2, invalidTimestamp,

and you wanted to implement:
select firstName, lastName, email, date, field1, field2 where
  firstName = \<fname> and
  lastName = \<lname> and
  email = \<email> and
  date = \<some date> and
  invalidTimestamp \<hasn't been set...so is "", or is null, or whatever the best way to indicate an unset timestamp would be>

What would that query look like?

**Comment by hawkfish** [comment]
`Expr.and` takes an arbitrary number of arguments, so you could just write this as a single `AND` with an argument list of `Expr.eq`s with two arguments.  And the check for null is just `Expr.isnull`.

**Comment by hawkfish** [comment]
```js
new FuncExpr(Expr.and, [
  new FuncExpr(Expr.eq, [new RefExpr('firstName'), "fname"]),
  new FuncExpr(Expr.eq, [new RefExpr('lastName'), "lname"])
  new FuncExpr(Expr.eq, [new RefExpr('email'), "email"])
  new FuncExpr(Expr.eq, [new RefExpr('date'), new Date(...)])
  new FuncExpr(Expr.isnull, [new RefExpr('invalidTimestamp')])
  ...
])
```

**Comment by hawkfish** [comment]
Does that help?

**Comment by presentoccupant** [comment]
Thanks!
