### ISSUE TITLE
Implement the BETWEEN function

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#66]
In a sheet that had, say, columns called date1 and date2, is there a "between" operator to get all rows where \<date> is between date1 and date2?

**Comment by hawkfish** [comment]
There is no between function, although there is no reason there couldn't be.  It is just `low <= x AND x <= high` though.

**Comment by hawkfish** [comment]
This is a perfectly fine feature request!

**Comment by presentoccupant** [comment]
Could you please provide an example of how to call the scalar functions?

**Comment by hawkfish** [comment]
I did add it to [the wiki](https://github.com/hawkfish/olapscript/wiki/Scalar-Functions#comparison-functions) - its not really any different from the other functions (it just has three arguments, labelled in the Wiki).

**Comment by presentoccupant** [comment]
I did look at the wiki, but it's not clear if they can be called directly (e.g., could I write "if .eq(2, 5)" or if I first need to have created an object to be able to use its scalars; if say, .eq could be applied to two entire columns - things like that).  So what do the scalars look like when called in their native habitat, as it were?

**Comment by hawkfish** [comment]
I added a bunch of examples to the scale function library. LMK if they help.

**Comment by presentoccupant** [comment]
Lovely; thank you!
