### ISSUE TITLE
Table.getRow() is 0-based

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#74]
...which would be fine, but it retrieves the first _data_ row, so there isn't a way to retrieve the header row, should you want it.

**Comment by hawkfish** [comment]
I think `table.ordinals` will give you what you want (and they Weill be in order too!)

**Comment by presentoccupant** [comment]
To clarify, table.ordinals is the header row (in order); Table.getRow(0) returns row 2 in the sheet.
