### ISSUE TITLE
Basic SQL expression parser

### ISSUE THREAD

**Issue by hawkfish** [hawkfish/olapscript#77]
If we ignore infix operators (+, AND, etc.) it is pretty straightforward to build an expression parser for SQL.  The infix operations will need to be expressed as functions (e.g., `AND(condition1, ...)`.

The main syntactic issue will just be that in SQL double quotes are used to delimit identifiers/references and single quotes are used for strings.  So if an expression needs both, it will have to be written using JavaScript's triple-quote mechanism.

**Comment by presentoccupant** [comment]
I presume legacy code would still work as well (at least through November), yes?

**Comment by hawkfish** [comment]
Not v0.2.0 so don't worry about it.  But yes, I plan to make it check for an expression being a string an then trying to parse it.
