### ISSUE TITLE
Not referencing the column correctly, apparently

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#78]
Please refer to the code in "ELR code.gs" - it's choking on the "where" clause and I'm having difficulty understanding why it doesn't like my RefExpr in my FuncExpr declaration.  (I realize you would likely not implement this routine quite this way, but it's nevertheless a good exercise.)

**Comment by hawkfish** [comment]
It's pretty simple actually - you changed the column name to `"name2"` when you `select`ed from `canonicalData`

**Comment by hawkfish** [comment]
I removed the `as` and it works now. I also added logging for the `Table.ordinals`, which makes the issue clearer.

**Comment by presentoccupant** [comment]
I am still getting an error (ReferenceError: Unknown column: Test Column), and although I can no longer locate the file "ELR code.gs," I found the code in olapscript-tests-and-utils.gs.  "new RefExpr('Test Column')," doesn't include an "as," so I'm not getting why I'm not specifying that column correctly.

**Comment by presentoccupant** [comment]
The routine you're looking for, in olapscript-tests-and-utils.gs, is "isBetween()," which is run via "testIsBetween()."

**Comment by presentoccupant** [comment]
OK.  This code works:

```js
function isBetween(low, high) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const target = helperTestSheet_(ss);
  const predicate = new FuncExpr( 
    function(testItem) {
      return low <= testItem && testItem <= high
    },
    [new RefExpr('Test Column')]
  );
  
  Table.fromSheet(ss.getSheetByName("test data2"))
    .select([
      {expr: new RefExpr('First'), as: 'firstName'},
      {expr: new RefExpr('Last'), as: 'lastName'},
      new RefExpr('Test Column'),
    ])
    .where(predicate)
    .toSheet(target)
  ;
}
```
but this code doesn't:
```js
function isBetween(low, high) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const target = helperTestSheet_(ss);
  const predicate = new FuncExpr( 
    function(testItem) {
      return low <= testItem && testItem <= high
    },
    [new RefExpr('Test Column')]
  );
  
  Table.fromSheet(ss.getSheetByName("test data2"))
    .select([
      {expr: new RefExpr('First'), as: 'firstName'},
      {expr: new RefExpr('Last'), as: 'lastName'},
//      new RefExpr('Test Column'),
    ])
    .where(predicate)
    .toSheet(target)
  ;
}
```
The second routine throws this error:  "ReferenceError: Unknown column: Test Column"

According to my understanding of SQL, the second routine _should_ work - I don't want to select 'Test Column'; I only want to select its brethren.

**Comment by hawkfish** [comment]
That's because in the second example you only selected `First` and `Last`.  In SQL, the two selects are:

```sql
SELECT "First" AS "firstName", "Last" AS "lastName", "Test Column"
SELECT "First" AS "firstName", "Last" AS "lastName"
```

You are correct that in SQL you can refer to columns in `WHERE` clauses that are not selected, but unfortunately the library can't do that kind of holistic semantic analysis of the query.  The library is more like what we DB people call a physical plan, which is like putting parentheses around everything:

```sql
SELECT *
FROM (
  SELECT "First" AS "firstName", "Last" AS "lastName", "Test Column"
  FROM "test data2"
) 
WHERE "Test Column" BETWEEN low AND high
```

All each operator knows about is what the previous one provided - they can't reach backwards and add columns.
