### ISSUE TITLE
Can I refer to a column by its letter, rather than its header?

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#84]
I have a situation in "Assign by Polling Place" sheet where I'm allowing up to five polling places to be assigned, but since the remaining four are optional, I only have a header name ("Polling place(s)") on the first column, column I.  Can I refer to the subsequent columns by their letter, or do I have to name those columns?

**Comment by presentoccupant** [comment]
Actually, there's a corollary to that question, and it has to do with the same example.  I don't know how to bundle the polling places up into an array (so that unnest will do the right thing) without doing this (the operative line being toRows():
```js
  const predicate = new FuncExpr( 
    function(isChecked) {
      return isChecked == true
    },
    [new RefExpr('Send?')]
  );
  let checked = Table.fromSheet(as)
    .select([
      new RefExpr('County'),
      new RefExpr('First'),
      new RefExpr('Last'),
      new RefExpr('Email'),
      new RefExpr('Phone'),
      new RefExpr('Send?'),
      new RefExpr('Date'),
      new RefExpr('Shift'),
//      new RefExpr('Rover?'),
      new RefExpr('Polling place(s)'),
      new RefExpr('J'),
      new RefExpr('K'),
      new RefExpr('L'),
      new RefExpr('M'),
    ])
    .where(predicate)
    .toRows()
  ;
```

- But what toRows() gives me isn't quite the same sort of array that I get in Apps Script, where I can index into its rows and columns - instead, it appears to give me an array of rows, each row consisting of name-value pairs.  That presents two conundra:
- I can't seem to use strings with spaces in them to access a particular field in the row (so I can't say "row.Polling place(s)" or row.'Polling place(s)' and for that matter I can't seem to have parentheses in there either; and
- OK, fine, I can change the associated column heading to be a string with no spaces and no parens, but would I really need to say
```js
let pPlaces = [];
if (row.pPlace1 != "")
  pPlaces.push(row.pPlace1);
if (row.pPlace2 != "")
  pPlaces.push(row.pPlace2);
if (row.pPlace1 != "")
  pPlaces.push(row.pPlace3);
if (row.pPlace4 != "")
  pPlaces.push(row.pPlace4);
if (row.pPlace5 != "")
  pPlaces.push(row.pPlace5);
```
Surely there's a better way; I just don't know what it is.

**Comment by hawkfish** [comment]
No, but that's a good feature request. Better than `Fn` for missing columns.

**Comment by presentoccupant** [comment]
And re my corollary question, is there a better way to reference those columns that as I described?

**Comment by hawkfish** [comment]
We now use the conventional spreadsheet names for missing columns.  The will get deduplicated too, so pathological situations like C,D,,, will produce C,D,C 2,D 2.

**Comment by presentoccupant** [comment]
Thanks!
