### ISSUE TITLE
toSheet should only clear the range to be written

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#86]
The more I think about it, the more I think that .toSheet shouldn't clear an entire sheet; it should just clear the range that will be written, even if that range always starts at A1.  At any rate, the utility of .toSheet is limited because it clears the entire sheet.  That said, clearing the entire sheet also seems like useful behavior, so maybe we want .toSheetRange in addition to .toSheet.

BTW, I'd call this a close relative of #79, rather than a dupe, though you might see that differently.

**Comment by hawkfish** [comment]
I would think `toSheetRange` would just be an option to `toSheet`.  And yes clearing is a separate issue from targeting.
