### ISSUE TITLE
Joins should support import column renaming

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#87]
How would I code up the following:
```
SELECT <fields>
FROM tableLeft L
LEFT JOIN tableRight R
ON L.key = R.key
WHERE R.key IS NULL
```
?

**Comment by hawkfish** [comment]
I think [tis example](https://github.com/hawkfish/olapscript/wiki/Apps-Script-Examples#finding-missing-values) is what you are looking for?

**Comment by presentoccupant** [comment]
Got it; thanks.  Just waiting for the edit to the .where statement and I can close this.

**Comment by hawkfish** [comment]
> Got it; thanks. Just waiting for the edit to the .where statement and I can close this.

Please don't! This is now an open issue.

**Comment by presentoccupant** [comment]
Will do...as it were...
